### ISSUE TITLE
Build.cs and XCodePostBuild.cs compile failed

### ISSUE THREAD

**Issue by Kotama520** [f111fei/react-native-unity-view#1]
when i Copy Build.cs to the unity project, i got some compile error message.

Assets/scripts/Editor/Build.cs(7,0): error CS1525: Unexpected symbol `<'
Assets/scripts/Editor/Build.cs(30,53): error CS1056: Unexpected character `��'
Assets/scripts/Editor/Build.cs(30,87): error CS1056: Unexpected character `��'
Assets/scripts/Editor/Build.cs(158,8): error CS1012: Too many characters in character literal
Assets/scripts/Editor/Build.cs(678,152): error CS1646: Keyword, identifier, or string expected after verbatim specifier: @
Assets/scripts/Editor/Build.cs(678,159): error CS1056: Unexpected character `\000a'
Assets/scripts/Editor/Build.cs(678,177): error CS1040: Preprocessor directives must appear as the first non-whitespace character on a line
Assets/scripts/Editor/Build.cs(678,184): error CS1040: Preprocessor directives must appear as the first non-whitespace character on a line
Assets/scripts/Editor/Build.cs(678,191): error CS1056: Unexpected character `\000a'
Assets/scripts/Editor/Build.cs(703,164): error CS1646: Keyword, identifier, or string expected after verbatim specifier: @
Assets/scripts/Editor/Build.cs(707,250): error CS1646: Keyword, identifier, or string expected after verbatim specifier: @
Assets/scripts/Editor/Build.cs(707,255+): error CS1009: Unrecognized escape sequence `\s'
Assets/scripts/Editor/Build.cs(707,255+): error CS1009: Unrecognized escape sequence `\S'
Assets/scripts/Editor/Build.cs(950,10): error CS1012: Too many characters in character literal
Assets/scripts/Editor/Build.cs(999,12): error CS1012: Too many characters in character literal

environment:
Windows7
Unity2017.3.1f1

**Comment by f111fei** [comment]
What's your `Assets/scripts/Editor/Build.cs` content ?

**Comment by Kotama520** [comment]
i made a mistake when i copied the Build.cs... now it's working, thank you.
