### ISSUE TITLE
Unity supported or recommended version

### ISSUE THREAD

**Issue by gavatron1010** [f111fei/react-native-unity-view#102]
@f111fei what version of Unity did you develop this module using? If you can recommend a Unity version I intend to switch my project to it in hopes of achieving greater stability.

**Comment by ziyoshams** [comment]
Looks like `2018.2.17f1` from commit messages to [react-native-unity-demo](https://github.com/f111fei/react-native-unity-demo).
<img width="526" alt="Screen Shot 2019-03-21 at 2 54 04 PM" src="https://user-images.githubusercontent.com/14338593/54777760-68d89b80-4be9-11e9-8771-54400330c7dc.png">
