### ISSUE TITLE
GetCloudProjectId crashes with Thread 1: EXC_BAD_ACCESS (code=1, address=0x0)

### ISSUE THREAD

**Issue by tffalls** [f111fei/react-native-unity-view#106]
I am getting a Thread 1: EXC_BAD_ACCESS (code=1, address=0x0) at GetCloudProjectId when I build my project from XCode to run it on my iPhone 6 (physical device).

I have looked at the solution to a related issue already on here (#84), but my Info.plist file already has the correct UnityCloudProjectID.

Does anyone know what could be causing this issue?

Unity Version: 2018.1.9f2
React Native Version: 0.57.2

**Comment by ziyoshams** [comment]
I don't use GetCloudProjectId, but most of the issues surface from using different Unity Versions. Use `2018.2.17` version. Download from here: https://unity3d.com/get-unity/download/archive

**Comment by tffalls** [comment]
@ziyoshams Unfortunately changing my Unity version ends up with the same error, thanks for the suggestion though

**Comment by aflahkp** [comment]
Hi @tffalls could you find any solutions for this issue. Any updates would be really helpful. Im getting the same error with Unity 2019.4 with UnityColudProjectID added in Info.plist.
