### ISSUE TITLE
Crashing on Samsung Note 8

### ISSUE THREAD

**Issue by gavatron1010** [f111fei/react-native-unity-view#111]
04-10 17:37:15.249  1409  1763 I InputDispatcher: Delivering touch to (8329): action: 0x0, toolType: 1
04-10 17:37:15.254  8329  8329 D ViewRootImpl@cc3cbbc[MainActivity]: ViewPostIme pointer 0
04-10 17:37:15.293  1409  1763 I InputDispatcher: Delivering touch to (8329): action: 0x1, toolType: 1
04-10 17:37:15.301  8329  8329 D ViewRootImpl@cc3cbbc[MainActivity]: ViewPostIme pointer 1
04-10 17:37:15.378  8329  8329 D SurfaceView: BG hide() Surface(name=Background for - SurfaceView - com.unitydroid5/com.unitydroid5.MainActivity@e681010@0) false true android.view.SurfaceView{e681010 VFE...... .F....ID 0,0-1440,2708}
04-10 17:37:15.395  8329  8329 V Surface : sf_framedrop debug : 0x4f4c, game : false, logging : 0
04-10 17:37:15.396  8329  8329 D SurfaceView: surfaceCreated 1 android.view.SurfaceView{e681010 VFE...... .F....ID 0,0-1440,2708}
04-10 17:37:15.396  8329  8329 D SurfaceView: surfaceChanged (1440,2708) 1 android.view.SurfaceView{e681010 VFE...... .F....ID 0,0-1440,2708}
04-10 17:37:15.402  8329  8329 V InputMethodManager: Starting input: tba=android.view.inputmethod.EditorInfo@393e709 nm : com.unitydroid5 ic=null
04-10 17:37:15.402  8329  8329 I InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
04-10 17:37:15.404 13712 13712 I SKBD    : SamsungKeypad [IMI] onStartInput - caller pid : 8329, caller uid : 10225
04-10 17:37:15.411  8329  8329 D ViewRootImpl@cc3cbbc[MainActivity]: Relayout returned: old=[0,0][1440,2960] new=[0,0][1440,2960] result=0x1 surface={valid=true 538698682368} changed=false
04-10 17:37:15.430  8329  8393 I Unity   : SystemInfo CPU = ARM64 FP ASIMD AES, Cores = 8, Memory = 5225mb
04-10 17:37:15.430  8329  8393 I Unity   : SystemInfo ARM big.LITTLE configuration: 4 big (mask: 0xf0), 4 little (mask: 0xf)
04-10 17:37:15.431  8329  8393 I Unity   : ApplicationInfo com.unitydroid5 version 1.0 build 77cac303-39d3-470d-8ebc-47056f1ff8b5
04-10 17:37:15.431  8329  8393 I Unity   : Built from '2018.3/release' branch, Version '2018.3.6f1 (a220877bc173)', Build type 'Release', Scripting Backend 'il2cpp', CPU 'arm64-v8a'
04-10 17:37:15.446  8329  8329 D ViewRootImpl@cc3cbbc[MainActivity]: Relayout returned: old=[0,0][1440,2960] new=[0,0][1440,2960] result=0x1 surface={valid=true 538698682368} changed=false
04-10 17:37:15.470  8329  8329 D ViewRootImpl@cc3cbbc[MainActivity]: Relayout returned: old=[0,0][1440,2960] new=[0,0][1440,2960] result=0x1 surface={valid=true 538698682368} changed=false
04-10 17:37:15.474  8329  8329 D SurfaceView: BG hide() Surface(name=Background for - SurfaceView - com.unitydroid5/com.unitydroid5.MainActivity@e681010@0) false true android.view.SurfaceView{e681010 VFE...... .F....ID 0,0-1440,2960}
04-10 17:37:15.478  8329  8329 D SurfaceView: surfaceChanged (1440,2960) 1 android.view.SurfaceView{e681010 VFE...... .F....ID 0,0-1440,2960}
04-10 17:37:15.487  8329  8329 D ViewRootImpl@cc3cbbc[MainActivity]: Relayout returned: old=[0,0][1440,2960] new=[0,0][1440,2960] result=0x1 surface={valid=true 538698682368} changed=false
04-10 17:37:15.634  8329  8393 E SchedPolicy: set_timerslack_ns write failed: Operation not permitted
04-10 17:37:15.670  8329  8393 D Unity   :  GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_vertex_half_float GL_OES_framebuffer_object GL_OES_rgb8_rgba8 GL_OES_compressed_ETC1_RGB8_texture GL_AMD_compressed_ATC_texture GL_KHR_texture_compression_astc_ldr GL_KHR_texture_compression_astc_hdr GL_OES_texture_compression_astc GL_OES_texture_npot GL_EXT_texture_filter_anisotropic GL_EXT_texture_format_BGRA8888 GL_OES_texture_3D GL_EXT_color_buffer_float GL_EXT_color_buffer_half_float GL_QCOM_alpha_test GL_OES_depth24 GL_OES_packed_depth_stencil GL_OES_depth_texture GL_OES_depth_texture_cube_map GL_EXT_sRGB GL_OES_texture_float GL_OES_texture_float_linear GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_EXT_texture_type_2_10_10_10_REV GL_EXT_texture_sRGB_decode GL_OES_element_index_uint GL_EXT_copy_image GL_EXT_geometry_shader GL_EXT_tessellation_shader GL_OES_texture_stencil8 GL_EXT_shader_io_blocks GL_OES_shader_image_atomic GL_OES_sample_variables GL_EXT_texture_border_clamp GL_EXT_multisampled_render_to_texture GL_EXT_mul
04-10 17:37:15.670  8329  8393 D Unity   : tisampled_render_to_texture2 GL_OES_shader_multisample_interpolation GL_EXT_texture_cube_map_array GL_EXT_draw_buffers_indexed GL_EXT_gpu_shader5 GL_EXT_robustness GL_EXT_texture_buffer GL_EXT_shader_framebuffer_fetch GL_ARM_shader_framebuffer_fetch_depth_stencil GL_OES_texture_storage_multisample_2d_array GL_OES_sample_shading GL_OES_get_program_binary GL_EXT_debug_label GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_QCOM_tiled_rendering GL_ANDROID_extension_pack_es31a GL_EXT_primitive_bounding_box GL_OES_standard_derivatives GL_OES_vertex_array_object GL_EXT_disjoint_timer_query GL_KHR_debug GL_EXT_YUV_target GL_EXT_sRGB_write_control GL_EXT_texture_norm16 GL_EXT_discard_framebuffer GL_OES_surfaceless_context GL_OVR_multiview GL_OVR_multiview2 GL_EXT_texture_sRGB_R8 GL_KHR_no_error GL_EXT_debug_marker GL_OES_EGL_image_external_essl3 GL_OVR_multiview_multisampled_render_to_texture GL_EXT_buffer_storage GL_EXT_external_buffer GL_EXT_blit_framebuffer_params GL_EXT_clip_cull_distance
04-10 17:37:15.670  8329  8393 D Unity   :  GL_EXT_protected_textures GL_EXT_shader_non_constant_global_initializers GL_QCOM_texture_foveated GL_QCOM_shader_framebuffer_fetch_noncoherent GL_EXT_memory_object GL_EXT_memory_object_fd GL_EXT_EGL_image_array GL_NV_shader_noperspective_interpolation
04-10 17:37:15.679  8329  8393 D libGLESv2: STS_GLApi : DTS, ODTC are not allowed for Package : com.unitydroid5
04-10 17:37:15.720  8329  8393 D         : PlayerBase::PlayerBase()
04-10 17:37:15.721  8329  8393 D         : TrackPlayerBase::TrackPlayerBase()
04-10 17:37:15.721  8329  8393 I libOpenSLES: Emulating old channel mask behavior (ignoring positional mask 0x3, using default mask 0x3 based on channel count of 2)
04-10 17:37:15.721  8329  8393 W AudioTrack: notificationFrames=-21 clamped to the range -1 to -8
04-10 17:37:15.723  8329  8393 I AudioTrack: AUDIO_OUTPUT_FLAG_FAST successful; frameCount 1536 -> 1536
04-10 17:37:15.723  8329  8393 D AudioTrack: Client defaulted notificationFrames to 192 for frameCount 1536
04-10 17:37:15.725  8329  8393 I AudioTrack: updateAudioTranstionLength FadeIn[0] FadeOut[0] FadeInRing[0]
04-10 17:37:15.725  1409  3463 D AudioPlaybackMonitor: Found a new active media playback. ID:759 -- type:OpenSL ES AudioPlayer (Buffer Queue) -- u/pid:10225/8329 -- state:started -- attr:AudioAttributes: usage=1 content=0 flags=0x0 tags= bundle=null
04-10 17:37:15.893  8329  8393 V MediaRouter: Adding route: RouteInfo{ name=Phone, description=null, status=null, category=RouteCategory{ name=System types=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO  groupable=false }, supportedTypes=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO , presentationDisplay=null }
04-10 17:37:15.899  8329  8393 V MediaRouter: Selecting route: RouteInfo{ name=Phone, description=null, status=null, category=RouteCategory{ name=System types=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO  groupable=false }, supportedTypes=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO , presentationDisplay=null }
04-10 17:37:15.908  8329  8393 W native  : commandlineflags.cc:972 Ignoring RegisterValidateFunction() for flag pointer 0x7d515dfde8: no flag found at that address
04-10 17:37:15.920  8329  8329 D ViewRootImpl@cc3cbbc[MainActivity]: Relayout returned: old=[0,0][1440,2960] new=[0,0][1440,2960] result=0x1 surface={valid=true 538698682368} changed=false
04-10 17:37:15.988  8329  8335 I zygote64: Do full code cache collection, code=101KB, data=103KB
04-10 17:37:15.989  8329  8335 I zygote64: After code cache collection, code=97KB, data=78KB
04-10 17:37:15.991  8329  8329 D SdkConfigurationReader: Fetched params from VrParamsProvider: # com.google.common.logging.Vr$VREvent$SdkConfigurationParams@98cb0e6e
04-10 17:37:15.991  8329  8329 D SdkConfigurationReader: allow_dynamic_java_library_loading: true
04-10 17:37:15.991  8329  8329 D SdkConfigurationReader: allow_dynamic_library_loading: true
04-10 17:37:15.991  8329  8329 D SdkConfigurationReader: allow_high_priority_app_render_thread: true
04-10 17:37:15.991  8329  8329 D SdkConfigurationReader: allow_passthrough: false
04-10 17:37:15.991  8329  8329 D SdkConfigurationReader: allow_vrcore_compositing: false
04-10 17:37:15.991  8329  8329 D SdkConfigurationReader: allow_vrcore_head_tracking: false
04-10 17:37:15.991  8329  8329 D SdkConfigurationReader: async_reprojection_config {
04-10 17:37:15.991  8329  8329 D SdkConfigurationReader:   additional_ahardwarebuffer_usage: 268435456
04-10 17:37:15.991  8329  8329 D SdkConfigurationReader:   back_rgb16_with_bgr16: true
04-10 17:37:15.991  8329  8329 D SdkConfigurationReader:   black_boost: 0
04-10 17:37:15.991  8329  8329 D SdkConfigurationReader:   compositor_draws_flange: true
04-10 17:37:15.991  8329  8329 D SdkConfigurationReader:   display_latency_micros: 900
04-10 17:37:15.991  8329  8329 D SdkConfigurationReader:   flags: 0
04-10 17:37:15.991  8329  8329 D SdkConfigurationReader:   scanout_offset_micros: 0
04-10 17:37:15.991  8329  8329 D SdkConfigurationReader:   scheduling_slack_micros: 1500
04-10 17:37:15.991  8329  8329 D SdkConfigurationReader:   strips_per_frame: 2
04-10 17:37:15.991  8329  8329 D SdkConfigurationReader:   vsync_grace_period_micros: 0
04-10 17:37:15.991  8329  8329 D SdkConfigurationReader: }
04-10 17:37:15.991  8329  8329 D SdkConfigurationReader: cpu_late_latching_enabled: false
04-10 17:37:15.991  8329  8329 D SdkConfigurationReader: daydream_image_alignment: ENABLED_WITH_MEDIAN_FILTER
04-10 17:37:15.991  8329  8329 D SdkConfigurationReader: dim_ui_layer: true
04-10 17:37:15.991  8329  8329 D SdkConfigurationReader: disallow_multiview: true
04-10 17:37:15.991  8329  8329 D SdkConfigurationReader: enable_forced_tracking_compat: false
04-10 17:37:15.991  8329  8329 D SdkConfigurationReader: screen_capture_config {
04-10 17:37:15.991  8329  8329 D SdkConfigurationReader:   allow_casting: true
04-10 17:37:15.991  8329  8329 D SdkConfigurationReader:   allow_screen_record: true
04-10 17:37:15.991  8329  8329 D SdkConfigurationReader:   allow_screenshot: true
04-10 17:37:15.991  8329  8329 D SdkConfigurationReader: }
04-10 17:37:15.991  8329  8329 D SdkConfigurationReader: touch_overlay_enabled: false
04-10 17:37:15.991  8329  8329 D SdkConfigurationReader: use_device_idle_detection: true
04-10 17:37:15.991  8329  8329 D SdkConfigurationReader: use_direct_mode_sensors: false
04-10 17:37:15.991  8329  8329 D SdkConfigurationReader: use_magnetometer_in_sensor_fusion: true
04-10 17:37:15.991  8329  8329 D SdkConfigurationReader: use_online_magnetometer_calibration: true
04-10 17:37:15.991  8329  8329 D SdkConfigurationReader: use_stationary_bias_correction: true
04-10 17:37:15.991  8329  8329 D SdkConfigurationReader: use_system_clock_for_sensor_timestamps: false
04-10 17:37:16.007  8329  8329 I zygote64: no shared libraies, dex_files: 1
04-10 17:37:16.034  8329  8329 W native  : commandlineflags.cc:972 Ignoring RegisterValidateFunction() for flag pointer 0x7d50d17fe8: no flag found at that address
04-10 17:37:16.039  8329  8329 I Ion     : [vr/gvr/capi/src/gvr_core_api_loader_android.cc:177] Successfully loaded GVR library version 1.200.0 from VrCore (target was 1.200.0).
04-10 17:37:16.135  8329  8329 I GVR     : [vr/gvr/capi/src/gvr.cc:104] Initialized GVR version 1.200.0
04-10 17:37:16.143  8329  8456 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
04-10 17:37:16.143  8329  8456 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
04-10 17:37:16.166  8329  8329 I GvrLayoutFactory: Successfully loaded GvrLayout from VrCore.
04-10 17:37:16.178  8329  8329 E SdkDaydreamTouchListener: Null deviceParams or no alignment markers found.
04-10 17:37:16.205  8329  8329 E SdkDaydreamTouchListener: Null deviceParams or no alignment markers found.
04-10 17:37:16.234  8329  8449 I GVR     : [vr/gvr/hmd/cardboard/cardboard_api_impl.cc:538] Creating swap chain with id: [1]
04-10 17:37:16.234  8329  8449 I GVR     : [vr/gvr/hmd/cardboard/cardboard_api_impl.cc:542]   BufferSpec 0: Size=V[2345, 2329], ColorFormat=Rgba8888, Samples=0, Views=1
04-10 17:37:16.234  8329  8449 I GVR     : [vr/gvr/hmd/cardboard/cardboard_api_impl.cc:542]   BufferSpec 1: Size=V[2345, 2329], ColorFormat=Rgba8888, Samples=0, Views=1
04-10 17:37:16.235  8329  8393 I Unity   : Created eye textures with a "separate" layout.  The "multi-pass" stereo mode will be used.
04-10 17:37:16.235  8329  8393 I Unity   : 
04-10 17:37:16.235  8329  8393 I Unity   :  
04-10 17:37:16.235  8329  8393 I Unity   : (Filename:  Line: 2264)
04-10 17:37:16.235  8329  8393 I Unity   : 
04-10 17:37:16.235  8329  8449 I GVR     : [vr/gvr/hmd/cardboard/cardboard_api_impl.cc:555] Destroying swap chain with id: [1]
04-10 17:37:16.235  8329  8449 I GVR     : [vr/gvr/hmd/cardboard/cardboard_api_impl.cc:538] Creating swap chain with id: [4]
04-10 17:37:16.235  8329  8449 I GVR     : [vr/gvr/hmd/cardboard/cardboard_api_impl.cc:542]   BufferSpec 0: Size=V[1642, 1630], ColorFormat=Rgba8888, Samples=0, Views=1
04-10 17:37:16.236  8329  8449 I GVR     : [vr/gvr/hmd/cardboard/cardboard_api_impl.cc:542]   BufferSpec 1: Size=V[1642, 1630], ColorFormat=Rgba8888, Samples=0, Views=1
04-10 17:37:16.273  8329  8393 D AudioTrack: stop() called with 26304 frames delivered
04-10 17:37:16.273  8329  8393 I AudioTrack: Skip ramp
04-10 17:37:16.273  8329  8393 D         : PlayerBase::stop() from IPlayer
04-10 17:37:16.284  8329  8329 D SurfaceView: BG hide() Surface(name=Background for - SurfaceView - com.unitydroid5/com.unitydroid5.MainActivity@e681010@0) false false android.view.SurfaceView{e681010 GFE...... ......I. 0,0-1440,2960}
04-10 17:37:16.285  8329  8329 D SurfaceView: surfaceDestroyed 1 android.view.SurfaceView{e681010 GFE...... ......I. 0,0-1440,2960}
04-10 17:37:16.286  8329  8329 D SurfaceView: BG destroy() Surface(name=Background for - SurfaceView - com.unitydroid5/com.unitydroid5.MainActivity@e681010@0) android.view.SurfaceView{e681010 GFE...... ......I. 0,0-1440,2960}
04-10 17:37:16.335  8329  8329 D ViewRootImpl@cc3cbbc[MainActivity]: Relayout returned: old=[0,0][1440,2960] new=[0,0][1440,2960] result=0x1 surface={valid=true 538698682368} changed=false
04-10 17:37:16.391  8329  8329 E SdkDaydreamTouchListener: Null deviceParams or no alignment markers found.
04-10 17:37:16.424  8329  8329 D ViewRootImpl@cc3cbbc[MainActivity]: Relayout returned: old=[0,0][1440,2960] new=[0,0][1440,2960] result=0x1 surface={valid=true 538698682368} changed=false
04-10 17:37:16.449  8329  8329 V Configuration:  needToUpdateOverlays
04-10 17:37:16.449  8329  8329 I chatty  : uid=10225(u0_a225) com.unitydroid5 identical 2 lines
04-10 17:37:16.449  8329  8329 V Configuration:  needToUpdateOverlays
04-10 17:37:16.454 13712 13712 I SKBD    : SamsungKeypad [IMI] onStartInput - caller pid : 8329, caller uid : 10225
04-10 17:37:16.466  8329  8329 D SensorManager: unregisterListener ::   
04-10 17:37:16.503  8329  8329 D ReactNative: ReactInstanceManager.detachViewFromInstance()
04-10 17:37:16.508  8329  8329 I Process : Sending signal. PID: 8329 SIG: 9
04-10 17:37:16.559 13712 13712 D InputEventReceiver: channel 'ClientState{483c549 uid 10225 pid 8329} (client)' ~ Disposing input event receiver.
04-10 17:37:16.559 13712 13712 D InputEventReceiver: channel 'ClientState{483c549 uid 10225 pid 8329} (client)' ~NativeInputEventReceiver.
04-10 17:37:16.559  1409  3463 I ActivityManager: Process com.unitydroid5 (pid 8329) has died: fore TOP (753,1885)
04-10 17:37:16.569  1409  2509 D InputDispatcher: Focus left window: 8329
04-10 17:37:16.617  1409  1546 W ActivityManager: setHasOverlayUi called on unknown pid: 8329
04-10 17:37:16.685 13712 13712 I SKBD    : SamsungKeypad [IMI] onStartInput - caller pid : 8329, caller uid : 10225
04-10 17:37:17.090 13712 13712 I SKBD    : SamsungKeypad [IMI] onStartInput - caller pid : 8329, caller uid : 10225

**Comment by JanOwiesniak** [comment]
@gavatron1010 how do you solve this issue?
