### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by tovesson** [f111fei/react-native-unity-view#14]
Is it possible to start the unity view only when at a certain screen? Now it seems like it starts in the background when the app i started and that leads to high CPU usage even when the view is not shown. I've tried using pause() and resume() but it doesn't seem to have that much of an affect.

**Comment by f111fei** [comment]
Yes, set `width` and `height` property.

Can you give me more information about performance ? example: screenshot, os, mobile.

**Comment by delgiudices** [comment]
@f111fei are you saying that setting `width: 0, height: 0` will reduce usage?

**Comment by f111fei** [comment]
@delgiudices 
No, I suggested use `pause()` and `resume()` at the right time

**Comment by mtostenson** [comment]
@tovesson Did you ever figure out a good approach? I'm doing something similar in my app and want to delay running the Unity view. My current plan is to default to an empty scene and see what kind of performance benefit that gets me. I'll only load in the real scene when ready.

**Comment by joruro** [comment]
@f111fei Why are you initing the unity view by default? Was there any restriction that made you do that?

**Comment by f111fei** [comment]
I am planning to start unity when UnityView is created.

**Comment by joruro** [comment]
I think it would be a good idea to make it optional. So when the view is rendered, it could start by default or it could be started using the `resume()` method

**Comment by f111fei** [comment]
fix https://github.com/f111fei/react-native-unity-view/commit/9fa48397bd51a4480be7727772099f108eaab64a and https://github.com/f111fei/react-native-unity-view/commit/61d3c146abab39fa111a86c509bba64d57f273db. please update to 1.2.2
