### ISSUE TITLE
building rn project on ios fails with: No matching function for call to 'objc_msgSend'

### ISSUE THREAD

**Issue by macrozone** [f111fei/react-native-unity-view#15]
i could successfully export the unity project, but building the react-native ios project fails with "No matching function for call to 'objc_msgSend'"

**Comment by f111fei** [comment]
What is your unity project? First step, It is recommended to use [Cube](https://github.com/f111fei/react-native-unity-demo/tree/master/unity/Cube) instead of.

**Comment by macrozone** [comment]
@f111fei i used an own simple one. 

I figured out, that this only happens on the simulator. It works only on a device

**Comment by nmsdvid** [comment]
Had the same problem, switching `Enable Strict Checking of objc_msgSend Calls` to `No` in `Build Settings` fixed the problem.

**Comment by fedegl** [comment]
If I try to run the project on the device I get the following error:

```
▸ Compiling RCTBundleURLProvider.m

❌  /Users/federico/code/react-native-unity-demo/node_modules/react-native/React/Base/RCTBundleURLProvider.m:17:53: use of undeclared identifier 'undefined'; did you mean 'underline'?

const NSUInteger kRCTBundleURLProviderDefaultPort = RCT_METRO_PORT;
                                                                     ^


▸ Compiling RCTLayoutAnimationGroup.m
▸ Compiling RCTNavigator.m
▸ Compiling RCTTabBar.m
** BUILD FAILED **


The following build commands failed:

	CompileC /Users/federico/code/react-native-unity-demo/ios/build/Build/Intermediates.noindex/React.build/Debug-iphoneos/React.build/Objects-normal/arm64/RCTBundleURLProvider.o Base/RCTBundleURLProvider.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)```

**Comment by edamazzio** [comment]
@nmsdvid 's solution caused 201 errors in my XCode project 🙃 Still haven't tried in a real device yet

**Comment by ham118** [comment]
> Had the same problem, switching `Enable Strict Checking of objc_msgSend Calls` to `No` in `Build Settings` fixed the problem.

Followed your steps but unable to run project in iOS. 😕

**Comment by amit00978** [comment]
I am facing the same problem during running the #react-native-unity-demo project `No matching function for call to objc_msgSend`.If anyone found the solution please help it's highly appreciated.
