### ISSUE TITLE
Execution failed for task ':UnityExport:BuildIl2CppTask'.

### ISSUE THREAD

**Issue by TeeRa0ne** [f111fei/react-native-unity-view#152]
Hi everyone,

I'm working on a project with this lib but i have error and i don't know how fix this :

 **What went wrong:
Execution failed for task ':UnityExport:BuildIl2CppTask'.**
> A problem occurred starting process 'command '/Users/xxxx/Desktop/xxxx/xxxx-react-native-cli/app/android/UnityExport/src/main/Il2CppOutputProject/IL2CPP/build/deploy/netcoreapp3.1/il2cpp.exe''`

Do you have a solution ?

**Comment by komalharmale** [comment]
> Hi everyone,
> 
> I'm working on a project with this lib but i have error and i don't know how fix this :
> 
> **What went wrong: Execution failed for task ':UnityExport:BuildIl2CppTask'.**
> 
> > A problem occurred starting process 'command '/Users/xxxx/Desktop/xxxx/xxxx-react-native-cli/app/android/UnityExport/src/main/Il2CppOutputProject/IL2CPP/build/deploy/netcoreapp3.1/il2cpp.exe''`
> 
> Do you have a solution ?

Did you find any solution

**Comment by komalharmale** [comment]
i am also facing same issue can you tell me the solution if you find any

**Comment by TeeRa0ne** [comment]
Yes i find a solution :

1. You need to have Unity on your PC, me i work with this version 2020.3.17f1 with this modules:
<img width="641" alt="Capture d’écran 2021-09-23 à 16 32 32" src="https://user-images.githubusercontent.com/60188443/134526912-d636bfdd-f8c7-40e2-8955-00ff118182b6.png">
2. Delete the UnityExport folder in Android folder of your project

3. And run a new build in Unity
<img width="1026" alt="Capture d’écran 2021-09-23 à 16 36 05" src="https://user-images.githubusercontent.com/60188443/134527508-2dec6e09-f34b-4137-a945-52c2a1d213ca.png">
 
I hope me solution will help you.
