### ISSUE TITLE
Newtonsoft not found

### ISSUE THREAD

**Issue by macrozone** [f111fei/react-native-unity-view#16]
in `UnityMessageManager` it does not find `Newtonsoft.JSON`

how to add this properly?

**Comment by vpsantos** [comment]
Hi macrozone,

You can see a sample with all necessary files here: https://github.com/f111fei/react-native-unity-demo

**Comment by f111fei** [comment]
https://github.com/f111fei/react-native-unity-demo/tree/master/unity/Cube/Assets/Scripts/Newtonsoft.Json

**Comment by macrozone** [comment]
thx guys! can we have this in the readme?

**Comment by f111fei** [comment]
@macrozone  Sure，But I busy with other things. Can you create a PR ?
