### ISSUE TITLE
how to use with cocoapods?

### ISSUE THREAD

**Issue by macrozone** [f111fei/react-native-unity-view#17]
Cocoapods sets its own config file `Pods-Pairs.debug`, so we can't use the custom `UnitiyConfig.xcconfig`, so i think we have to change `UnitiyConfig` to extend   `Pods-Pairs.debug` but i have no clue how to do that. Any advice?

**Comment by f111fei** [comment]
Try marge `Pods-Pairs.debug` to `UnitiyConfig.xcconfig`.

**Comment by macrozone** [comment]
this seems to work:

`#include "Pods/Target Support Files/Pods-Pairs/Pods-Pairs.debug.xcconfig"`

**Comment by im-aditya** [comment]
Hey,

I think I am having the same issue. My react native project is using cocoapods and when I change the config to UnityConfig.xcconfig I am getting this error:

```
diff: /Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

```

Any idea how to fix this ?

**Comment by im-aditya** [comment]
@macrozone : Where did you add this #include line ?

Thanks
