### ISSUE TITLE
How to configure the project, If I have multiple scenes ?

### ISSUE THREAD

**Issue by Jornason** [f111fei/react-native-unity-view#18]
It works in single scene, 
How to configure the project, If I have multiple scenes?  Like specify the scenes order...

**Comment by f111fei** [comment]
You can send messages to Unity to switch the scene.

**Comment by Jornason** [comment]
Thanks for reply, I've found the following code:
```
    static string[] GetEnabledScenes()
    {
        var scenes = EditorBuildSettings.scenes
            .Where(s => s.enabled)
            .Select(s => s.path)
            .ToArray();

        return scenes;
    }
```
Like normal "Build Settings" configuration, I can select enabled scenes and switch them via messages.
