### ISSUE TITLE
Getting Error Unsupported Architecture

### ISSUE THREAD

**Issue by nmsdvid** [f111fei/react-native-unity-view#19]
Hello I'm getting an error Unsupported Architecture when trying to run on a real device, on simulator its working. Do you have an idea what could be the problem ? 
<img width="292" alt="screen shot 2018-06-13 at 10 59 45" src="https://user-images.githubusercontent.com/1606990/41340986-e9e0404e-6ef8-11e8-917b-36e938e4d918.png">

**Comment by fluiddot** [comment]
Probably that's due to the configuration of your PlayerSettings, check the value of `Target SDK`.
You need to change it depending on where you want build:
Simulator => Target SDK = Simulator SDK
Device => Device SDK
