### ISSUE TITLE
Vuforia datasets don't load

### ISSUE THREAD

**Issue by Charlynux** [f111fei/react-native-unity-view#20]
We clone the react-native-unity-demo repository for "POCing around" with Unity + React Native. Wanting to play with some Vuforia, we add an ARCamera and an ImageTarget (with predefined assets).
When we build the project in Unity, AR works with no problem, but when we export it then install it on an iOS device, it doesn't work.

The application start, with the camera view (including the Vuforia watermark), but recognition doesn't work.
In logs, we found this line : 
`Dataset VuforiaMars_Images could not be loaded and cannot be activated.`

I can see the files in UnityExport/Data/Raw/Vuforia, but maybe Vuforia search in an other directory ?

I don't know how to find more debugging informations, so any tip would be appreciated.

**Comment by Charlynux** [comment]
I fixed it !

During my search, I quickly found informations [here](https://developer.vuforia.com/forum/ios/dataset-exists-fails-load-and-activate).
But LoadDatabaseBehaviour doesn't exist anymore in Vuforia 7. By the way, the function AddExternalDatasetSearchDir is still in the documentation. I discover [here](https://gitlab.cs.ucl.ac.uk/vania/team27website/blob/d8e1335d1a77dd9a6ce215ada1b08e0bd479e51a/project/Assets/Vuforia/Scripts/VuforiaBehaviour.cs) how to call it in Unity code.

To fix the problem, I add a component "script" on the ARCamera. With the following code :
```
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Vuforia;

public class DataSetLoadController : MonoBehaviour {

	// Use this for initialization
	void Start () {
		var databaseLoader = DatabaseLoadARController.Instance;
		databaseLoader.AddExternalDatasetSearchDir(Application.dataPath + "/Raw/Vuforia/");
	}
	
	// Update is called once per frame
	void Update () {
		
	}
}
`
`` 

Just rebuild the project (Unity + iOS) and it works !

**Comment by JanOwiesniak** [comment]
@Charlynux how do you even came this far :) ? I'm stucked in the compiling process. Do you have any tip on [that](https://github.com/f111fei/react-native-unity-view/issues/68)?
