### ISSUE TITLE
react-native-unity-view and Vuforia

### ISSUE THREAD

**Issue by stajics** [f111fei/react-native-unity-view#22]
I am trying to setup react-native-unity-view with unity app that uses vuforia ARCamera and ImageTarget. App runs and i can see the camera, but its not detecting the image. (I am using a vuforia 5 star sample image and it works when i test it in Unity so that part is not the problem).
Any ideas why its not triggering tracking events? It looks like everything initializes good because i send couple of messages from ImageTarget to react native with UnityMessageManager.Instance.SendMessageToRN and they are received good.

**Comment by Charlynux** [comment]
I built a project with Vuforia last week.
I encountered two problems :
- On iOS, datasets was not found.
https://github.com/f111fei/react-native-unity-view/issues/20

- On Android, camera doesn't autofocus.
https://medium.com/@harmittaa/setting-camera-focus-mode-for-vuforia-arcamera-in-unity-6b3745297c3d

Hope this help.
