### ISSUE TITLE
Missing UnityExport folders?

### ISSUE THREAD

**Issue by kevando** [f111fei/react-native-unity-view#23]
I had trouble getting this to work, so then I got the demo app to work and compared what was different. I had to add the UnityExport folders myself. 

```
- UnityExport
-- Classes
-- Libraries
-- Data
``` 

were not there. screenshot = https://i.imgur.com/fbjW4Pb.png

Did I miss something?

**Comment by edamazzio** [comment]
Is the UnityExport folder actually located at YourRNProyect/ios/UnityExport ?

**Comment by Frulko** [comment]
Have you set the same Project Name in your Unity project settings page as your React Native project .xcodeproj name ?
