### ISSUE TITLE
Android compile error with Unity 2018.2 

### ISSUE THREAD

**Issue by pauberson** [f111fei/react-native-unity-view#25]
After upgrading the Unity project to 2018.2 there are compile errors when building for Android. It can't find the com.unity3d.player classes.

I've worked around this by adding:

    implementation files('../../../android/UnityExport/libs/unity-classes.jar')

to the dependencies at the bottom of:

node_modules/react-native-unity-view/android/build.gradle

but don't know if there's a better way of fixing this?

**Comment by im-aditya** [comment]
I am having the same issue...

**Comment by benjamin-bjorklund** [comment]
Same here using latest Unity version (2018.2.2f1).

**Comment by f111fei** [comment]
pls update to 1.2.0
