### ISSUE TITLE
error in run project

### ISSUE THREAD

**Issue by ali226281** [f111fei/react-native-unity-view#26]
when I run Project show this massage.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':react-native-unity-view'.
      > Could not resolve all dependencies for configuration ':react-native-unity-view:_debugPublish'.
         > Configuration with name 'default' not found.

**Comment by vuthanhtrung0504** [comment]
what is the solution? i have the same problem
