### ISSUE TITLE
UnityExport Folder Big Size

### ISSUE THREAD

**Issue by frankyveras** [f111fei/react-native-unity-view#33]
When Cube Game/Scene is extracted , you get the UnityExport folder , but this folder is too big , over 700 MB , can this be reduced ?

![image](https://user-images.githubusercontent.com/7468706/43207037-11604ad4-8ff5-11e8-9d14-7c7123355098.png)

**Comment by f111fei** [comment]
It doesn't matter. This is only the size of the development, not the release. `libiPhone-lib.a` is about 540MB. We can't reduce this.
You can compare the size of original unity project after archive.

**Comment by frankyveras** [comment]
Thanks!!!!
