### ISSUE TITLE
2 duplicate symbols for architecture arm64

### ISSUE THREAD

**Issue by im-aditya** [f111fei/react-native-unity-view#37]
Hi,

In my project I am using [react-native-splash-screen](https://github.com/crazycodeboy/react-native-splash-screen) which has SplashScreen.h file. This project also has SplashScreen.h file which is conflicting with my other library.

Anyway to resolve this ? I don't need SplashScreen from Unity.

Thanks

**Comment by f111fei** [comment]
https://github.com/crazycodeboy/react-native-splash-screen/pull/238

update to `react-native-splash-screen@3.1.0`

**Comment by im-aditya** [comment]
Thanks for the quick reply. This fixes it.
