### ISSUE TITLE
Use of undeclared identifier 'UnityInitStartupTime' (iOS)

### ISSUE THREAD

**Issue by edamazzio** [f111fei/react-native-unity-view#40]
UnityExport/Classes/main.mm

![image](https://user-images.githubusercontent.com/9098480/43545962-958dc6b6-9594-11e8-80e8-10e51a2f48ae.png)

Can't seem to find a solution to this. Tried removing reference to UnityExport, then building again with no luck. Any suggestions?

Using 
Unity 2018.1.1f1
Xcode 9.4 Build version 9F1027a
react-native: 0.55.4

Thanks

**Comment by edamazzio** [comment]
Closing as I couldn't reproduce this issue myself again.

**Comment by liamloyalty** [comment]
I'm still getting this issue. @edamazzio How did you fix this? Any help would be much appreciated as using in a critical project!!
@f111fei 
Thanks very much in advance


I have tried using both Unity 2018.2.1 8f1 and Unity 2018.2.1 7f1 
"react-native": "0.57.0"

**Comment by edamazzio** [comment]
I'm sorry, but as I stated before, I couldn't reproduce the issue again, and also I'm not part of the project this issue was related with. You'd better create a new issue.

Good luck

**Comment by tushar-iosd** [comment]
Hey @liamloyalty did you fix it ? and if yes ? how ?

**Comment by 12343954** [comment]
same issue +1
