### ISSUE TITLE
Send parameters between React and Unity side

### ISSUE THREAD

**Issue by hersonrodrigues** [f111fei/react-native-unity-view#42]
What is the best way to send parameters between React side and Unity side?

O would like to send something like...

```
var jsonParam = JSON.stringify({color:1});
unity.postMessage('Cube', 'setColor', jsonParam);
```

and automatically receive on method setColor(int color) on React side,

is it possible? some suggestion to do it?

**Comment by f111fei** [comment]
Suggested use [`UnityMessageManager`](https://github.com/f111fei/react-native-unity-demo/blob/master/unity/Cube/Assets/Scripts/UnityMessageManager.cs)

You can find the usage in https://github.com/f111fei/react-native-unity-demo
