### ISSUE TITLE
How to disable unity view during development to be able to run on simulators

### ISSUE THREAD

**Issue by delgiudices** [f111fei/react-native-unity-view#47]
Things are fine, I just want to be able to develop on the simulator, what are you guy doing to solve this?

**Comment by ercpereda** [comment]
It works in the android emulator even with the **UnityView**.

**Comment by alisherakb** [comment]
> Things are fine, I just want to be able to develop on the simulator, what are you guy doing to solve this?

1. Delete UnityExport folder
2. Delete libRNUnityView from Link Binary with Library
3. Change main.m in Xcode to 
`int main(int argc, char * argv[]) {
  @autoreleasepool {
    return UIApplicationMain(argc, argv, nil, NSStringFromClass([AppDelegate class]));
  }`

To run on the real device again just recreate the reverse process.
