### ISSUE TITLE
"UnityView" was not found in the UIManager

### ISSUE THREAD

**Issue by willienchen** [f111fei/react-native-unity-view#48]
![2018-08-14 7 16 33](https://user-images.githubusercontent.com/10320670/44088572-364ea604-9ff6-11e8-8a3b-3a401157df0f.png)

**Comment by itinance** [comment]
How did you solved this?

**Comment by willienchen** [comment]
> How did you solved this?

This is the test I did a long time ago.
Maybe use device can solved this

**Comment by shah0664** [comment]
I am getting this on a real device, can you please help to fix this
