### ISSUE TITLE
error: Build input file cannot be found: Bulk_UnityEngine.UnityConnectModule_0.cpp

### ISSUE THREAD

**Issue by omer-halici** [f111fei/react-native-unity-view#59]
Hi,
I am trying to build this demo on my mac which has unity 2018.2.11f1 and xcode version 10.0. I am getting the following error:

error: Build input file cannot be found: '/Users/myUser/Desktop/react-native-unity-demo-master/ios/UnityExport/Classes/Native/Bulk_UnityEngine.UnityConnectModule_0.cpp'

Any ideas?

**Comment by hungdt-ibl** [comment]
@omer-halici did you fixed it ?

**Comment by amit00978** [comment]
@hungdt-ibl  did you fixed the issue?. I am facing the same issue. any help highly appreciated.
