### ISSUE TITLE
Unity, Xcode, Vuforia versions 

### ISSUE THREAD

**Issue by mercem** [f111fei/react-native-unity-view#60]
Hi,

 I m trying to use react-native with unity but I need to ask some question: 

1. Is this compatible with newer versions of unity? (versions greater than 2018.1)

2. Is this compatible with newer versions of xcode?

3. Is this compatible with vuforia? ( I have read issues about vuforia.)

4. Is this compatible with newer version of react-native?

I already have unity project, however, using unity solely is not efficient. I want to benefit from ui elements and huge libraries of react-native. I need to know if this beautiful component may stop working in the future?  Thank you for your effort. This project is awesome!

**Comment by f111fei** [comment]
1. yes
2. yes
3. yes
4. yes
