### ISSUE TITLE
Build issue with no error

### ISSUE THREAD

**Issue by ShaubertIlya** [f111fei/react-native-unity-view#62]
Hello and good day. I've imported unity-view library as it said in the tutorial but when I'm trying to run-android build fails with no error.

Execution failed for task ':app:packageDebug'.
> org.gradle.tooling.BuildException (no error message)

react-native-unity-view: 1.1.5
react-native-cli: 2.0.1
react-native: 0.57.1

Can this issue be related to a unity version? I'm using unity 2017.1.1f1

**Comment by f111fei** [comment]
Readme https://github.com/f111fei/react-native-unity-demo

Unity2018 is recommended.

**Comment by ShaubertIlya** [comment]
Can I use unity-view with unity 2017.1.1?

**Comment by f111fei** [comment]
Yes, See https://github.com/f111fei/react-native-unity-demo/tree/unity-2017
But 2017 is no longer maintained.

**Comment by ShaubertIlya** [comment]
Thank's a lot
