### ISSUE TITLE
Project with path ':Firebase' could not be found in project ':UnityExport'

### ISSUE THREAD

**Issue by ShaubertIlya** [f111fei/react-native-unity-view#64]
Hello and good day. I've installed react-native-unity-view as it mentioned in the instruction and exported Unity project. When i try to run-android it gives me an error.

A problem occurred evaluating project ':UnityExport'.
> Project with path ':Firebase' could not be found in project ':UnityExport'.

Here is the structure of the folders inside of UnityExport:

![image](https://user-images.githubusercontent.com/35298274/47836375-437df900-ddd2-11e8-9d69-5d61c9701757.png)

Could you tell please, what's wrong? 

react-native-cli: 2.0.1
react-native: 0.57.1
react-native-unity-view: ^1.1.5,
react-native-firebase: ^5.0.0,
Unity engine version: 2018.2.14f1

**Comment by ShaubertIlya** [comment]
Finally i've found what the problem was. Look's like i can't use firebase or any libraries connected to Google Play in Unity if i use with react-native-unity-view

**Comment by ziyoshams** [comment]
Can you please provide more insight. What do you mean by libraries connected to Google play. I have similar issue. I have this error: ```A problem occurred evaluating project ':UnityExport'.
> Could not find method google() for arguments [] on repository container.
```

**Comment by ShaubertIlya** [comment]
Hello. My error had been provided by Firebase library in Unity project. I solved it by deleting firebase from my Unity project. Think it does make sense use Firebase only in react-native project

**Comment by lorenzogm** [comment]
Any idea how to use google services and react-native-unity-view together?

**Comment by lorenzogm** [comment]
Reading previous comments I thought the issue was in "react-native-unity-view", but there is no conflict between firebase (or google services) and "react-native-unity-view". The conflict was with the project exported from unity.

Maybe, google services are not needed in the unity project if you have RN. But it would be nice to find a solution to have google services in RN and in unity.

**Comment by ziyoshams** [comment]
Are you using the latest version of unity view?
