### ISSUE TITLE
Not an issue,but info needed on Limitations of this module

### ISSUE THREAD

**Issue by abhi06991** [f111fei/react-native-unity-view#7]
Hi, First of all thanx for your amazing work.  I am pretty new to unity and react-native. I am developing an android application using react-native. So before I go into using it, I just want to know a few things:

1) Will we be able to fully utilise the power of unity using this component? For e.g: I would want my users to interact with the 3D Objects, is that even possible?
2) If there are any limitations of this module, what would that be?

Thank you!

**Comment by f111fei** [comment]
1. Yes, The module can send meesages to unity, and receive mesaages from unity.
2. I think the limitation is that only one UnityView can be displayed at the same time.

**Comment by Jornason** [comment]
It would be perfact, If this project can support react native in windows and osx.

https://github.com/Microsoft/react-native-windows

https://github.com/ptmt/react-native-macos
