### ISSUE TITLE
UnityView displaying by default

### ISSUE THREAD

**Issue by adilosa** [f111fei/react-native-unity-view#70]
Tried the demo project, and after the React splash screen, the UnityView immediately displays – without the instructions and toggle button overlay. Is there a way to prevent the UnityView from auto-launching on top of React?

**Comment by sunsshadow** [comment]
I experienced the same issue and the React overlay appears to be working on Unity 2018.1.3f1 but not 2018.4.16f. Does anyone know how to make it work with Unity 2018.4.16f?

Thanks!

**Comment by hungdt-ibl** [comment]
same problems. With unity 2018.4.16

**Comment by mhjalmarson** [comment]
I have the same problems with 2018.4.15 - 2018-4.17.

**Comment by f111fei** [comment]
fix https://github.com/f111fei/react-native-unity-view/commit/7b60e57389f3f7ad2ff6de7d0574041db8ac9729

Please update to 1.2.1 and update [XCodePostBuild.cs](https://github.com/f111fei/react-native-unity-demo/blob/ca4bde8af6b8b43079aeb5abeb4cd5e3f29d8bcc/unity/Cube/Assets/Scripts/Editor/XCodePostBuild.cs)
