### ISSUE TITLE
Android UnityView and childrenView problem

### ISSUE THREAD

**Issue by techistoner** [f111fei/react-native-unity-view#76]
first i have the same Configuration with demo,then build and run the android app
There are two cases：
1.use untiyView like a children  ，code blow:
    <View style={{flex:1}}>

            <UnityView style={{flex:1,justifyContent: 'space-between' }}
                       onMessage={this.onMessage.bind(this)}
            >
                </UnityView>

                </View>
this is very nice success.
2. insert a view into UnityView ，and crash
    <View style={{flex:1}}>

            <UnityView style={{flex:1,justifyContent: 'space-between' }}
                       onMessage={this.onMessage.bind(this)}
            >
                <View style={{width:50,height:50,backgroundColor:'white',position:'absolute',bottom:0}}>

                </View>
                </UnityView>

                </View>
error mes:com.reactnative.unity.view.UnityViewManager cannot be cast to com.facebook.react.uimanager.ViewGroupManager
manageChildren
NativeViewhierarchyManager.java:357
........

but it is out of question in iOS.

**Comment by f111fei** [comment]
It will be repaired soon.

**Comment by techistoner** [comment]
> It will be repaired soon.

thanks so much ,i am working on android project . Really looking forward to

**Comment by f111fei** [comment]
Please update to 1.3.0

**Comment by techistoner** [comment]
> Please update to 1.3.0

i have update to 1.3.0 but it don't work for me

**Comment by f111fei** [comment]
```
render() {
  const { renderUnity, unityPaused, clickCount } = this.state;
  let unityElement: JSX.Element;

  if (renderUnity) {
    unityElement = (
      <UnityView
        style={{ position: 'absolute', left: 0, right: 0, top: 0, bottom: 0 }}
        onUnityMessage={this.onUnityMessage.bind(this)}
      >
        <View style={{ width: 50, height: 50, backgroundColor: 'white', position: 'absolute', bottom: 0 }} />
      </UnityView>
    );
  }

  return (
    <View style={[styles.container]}>
      {unityElement}
      <Text style={styles.welcome}>
        Welcome to React Native!
      </Text>
      <Text style={{ color: 'black', fontSize: 15 }}>Unity Cube Click Count: <Text style={{ color: 'red' }}>{clickCount}</Text> </Text>
      <Button label="Toggle Unity" style={styles.button} onPress={this.onToggleUnity.bind(this)} />
      {renderUnity ? <Button label="Toggle Rotate" style={styles.button} onPress={this.onToggleRotate.bind(this)} /> : null}
      {renderUnity ? <Button label={unityPaused ? "Resume" : "Pause"} style={styles.button} onPress={this.onPauseAndResumeUnity.bind(this)} /> : null}
    </View>
  );
}
```


![screen](https://user-images.githubusercontent.com/7069719/49986014-2891cd80-ffa9-11e8-86d0-77b07e028d36.png)

**Comment by techistoner** [comment]
> ```
> render() {
>   const { renderUnity, unityPaused, clickCount } = this.state;
>   let unityElement: JSX.Element;
> 
>   if (renderUnity) {
>     unityElement = (
>       <UnityView
>         style={{ position: 'absolute', left: 0, right: 0, top: 0, bottom: 0 }}
>         onUnityMessage={this.onUnityMessage.bind(this)}
>       >
>         <View style={{ width: 50, height: 50, backgroundColor: 'white', position: 'absolute', bottom: 0 }} />
>       </UnityView>
>     );
>   }
> 
>   return (
>     <View style={[styles.container]}>
>       {unityElement}
>       <Text style={styles.welcome}>
>         Welcome to React Native!
>       </Text>
>       <Text style={{ color: 'black', fontSize: 15 }}>Unity Cube Click Count: <Text style={{ color: 'red' }}>{clickCount}</Text> </Text>
>       <Button label="Toggle Unity" style={styles.button} onPress={this.onToggleUnity.bind(this)} />
>       {renderUnity ? <Button label="Toggle Rotate" style={styles.button} onPress={this.onToggleRotate.bind(this)} /> : null}
>       {renderUnity ? <Button label={unityPaused ? "Resume" : "Pause"} style={styles.button} onPress={this.onPauseAndResumeUnity.bind(this)} /> : null}
>     </View>
>   );
> }
> ```
> ![screen](https://user-images.githubusercontent.com/7069719/49986014-2891cd80-ffa9-11e8-86d0-77b07e028d36.png)
thanks ,i am not uninstall old apk .it works!
