### ISSUE TITLE
Use of undeclared identifier 'UnityInitStartupTime' (iOS)

### ISSUE THREAD

**Issue by Arnaod** [f111fei/react-native-unity-view#81]
in file 'UnityExport/Classes/main.mm'

<img width="1048" alt="capture d ecran 2019-01-07 a 18 14 44" src="https://user-images.githubusercontent.com/6739306/50782453-55838880-12a8-11e9-813e-e19f8810ff2a.png">

There was a similar issue  #40 , closed without solution since the user couldn't reproduce it.
I tried removing reference to UnityExport, then building again but it didn't change anything.

Using:
Unity 2018.2.19f1
Xcode Version 10.1
react-native: 0.57.4

Thanks for any insight !

**Comment by Arnaod** [comment]
UnityExport/Classes/Unity is indeed in the header search path (taken care of by xconfig throught $(inherited) ).
I can include UnityInterface.h in main.mm to "solve" the issue but I seem to run into some circular include

**Comment by Arnaod** [comment]
Issue was , for some reason, that we didn't have $(SRCROOT)/UnityExport/Classes/Prefix.pch in build settings > prefix header

**Comment by 12343954** [comment]
same issue +1
