### ISSUE TITLE
Unity View with ARkit

### ISSUE THREAD

**Issue by vikas5914** [f111fei/react-native-unity-view#9]
Hi, 

I try to use this with ARKit. I used official unity ARKit plugin. 
I added the ARKit.framework in Linked framework and Libraries.

it working but there are some problems. 

1) It takes around 1 min to start the application. (from splash screen to unity view)
2) It only runs if I have Xcode running. App gets crashed if it is not run from Xcode. 
3) When I tried to make an archive, I am getting this error: library not found for -lRNUnityView

This is Xcode Log: https://hastebin.com/xaxicepozu.rb

**Comment by vikas5914** [comment]
Files: https://wetransfer.com/downloads/1cf44ba0f50c4b617e764d3005bba62a20180409160725/00255cc7407baf01ca623249304c07b720180409160725/f46e29

**Comment by f111fei** [comment]
Thanks，I will have a look later.

**Comment by vikas5914** [comment]
@f111fei Hey, any update?

**Comment by briancalvium** [comment]
I also had a bit of trouble getting this going in release. I managed to solve the library not found error by adding RNUnityView as a target dependency in Target->Build Phases. It seemed to get stripped out otherwise in Release. Then, I had to disable bitcode for the RNUnityView project to squash an 'invalid bitcode' error. Hope that helps!

**Comment by alisherakbarov** [comment]
Any updates on Unity-ARkit view inside React native? Is it possible?
We are facing some errors related with libRNUnityView, GetAppController  

<img width="863" alt="screen shot 2018-05-11 at 20 46 48" src="https://user-images.githubusercontent.com/26904008/39938719-8393d144-555c-11e8-8e54-e2f2ad136094.png">

**Comment by f111fei** [comment]
@alisherakbarov  https://github.com/f111fei/react-native-unity-demo/issues/5#issuecomment-387748059
