### ISSUE TITLE
App going from Background to Active mode Memory Increase

### ISSUE THREAD

**Issue by ziyoshams** [f111fei/react-native-unity-view#92]
Hi fellow developers and thank you @f111fei for this awesome package. I am having issues with memory usage which eventually crashes the app. When going back and forth from `background` to `active` mode and vice versa the apps memory usage increases dramatically. I am wondering if `UnityView` as the best practice, should be removed when going to `background` mode and re-instantiated in `active`. I have no clue. Anyone has any advice?

**Comment by JanOwiesniak** [comment]
Depending on the application, booting Unity could take some time (e.g. in my case) so automatically destroying unity everytime the user pushes the app into background is clearly something i don't want to happen.

Something like `destroyUnity` which could be the counterpart to [createUnity](https://github.com/f111fei/react-native-unity-view#createunity-promiseboolean) could be a good approach to pass the decision-making process to the developer.

**Comment by ziyoshams** [comment]
I would prefer not to destroy the view, but I can't seem to find the source of memory leak.
