### ISSUE TITLE
Thread 1: EXC_BAD_ACCESS (code=1, address=0x88)

### ISSUE THREAD

**Issue by alisherakb** [f111fei/react-native-unity-view#98]
App is crashing after on launching <UnityView />
<img width="1024" alt="Screenshot 2019-03-15 at 11 40 33 AM" src="https://user-images.githubusercontent.com/26904008/54422439-2c9fc980-4717-11e9-9bf0-431a41f6fd80.png">

What can cause the issue?

Unity: 2018.2.17
"react-native": 0.58.6

**Comment by alisherakb** [comment]
@JanOwiesniak  Have you ever experienced that behavior?

**Comment by JanOwiesniak** [comment]
Yes i ran into this issue several times.

It can be caused by a lot of stuff, sadly there is no general solution to this issue.

> In summary, when you run into EXC_BAD_ACCESS, it means that you try to send a message to a block of memory that can't execute that message.
> 
> In some cases, however, EXC_BAD_ACCESS is caused by a corrupt pointer. Whenever your application attempts to dereference a corrupt pointer, an exception is thrown by the kernel.

In my particular case (i think) i lost a pointer to a 3rd party library (Vuforia) which resulted in this crash:

```
Vuforia::init()
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000992616966020
```

[This workflow helped me fix this issue](https://github.com/f111fei/react-native-unity-view/issues/79#issuecomment-466628920).
I think step 8. (keeping a reference to the unity module was the game changer)

---

Another time i had issues with combination of `react-navigation` and `UnityModule.createUnity`.
You can read more [here](https://github.com/f111fei/react-native-unity-view/issues/93#issuecomment-465092499).

**Comment by alisherakb** [comment]
> Yes i ran into this issue several times.
> 
> It can be caused by a lot of stuff, sadly there is no general solution to this issue.
> 
> > In summary, when you run into EXC_BAD_ACCESS, it means that you try to send a message to a block of memory that can't execute that message.
> > In some cases, however, EXC_BAD_ACCESS is caused by a corrupt pointer. Whenever your application attempts to dereference a corrupt pointer, an exception is thrown by the kernel.
> 
> In my particular case (i think) i lost a pointer to a 3rd party library (Vuforia) which resulted in this crash:
> 
> ```
> Vuforia::init()
> EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000992616966020
> ```
> [This workflow helped me fix this issue](https://github.com/f111fei/react-native-unity-view/issues/79#issuecomment-466628920).
> I think step 8. (keeping a reference to the unity module was the game changer)
> 
> Another time i had issues with combination of `react-navigation` and `UnityModule.createUnity`.
> You can read more [here](https://github.com/f111fei/react-native-unity-view/issues/93#issuecomment-465092499).

In my case it's related somehow with "validateTextureDimensions, line 1074: error 'MTLTextureDescriptor has width of zero.'
validateTextureDimensions:1074: failed assertion `MTLTextureDescriptor has width of zero.'
(lldb) " in UnityExport/Classes/Unity/MetalHelper.mm

Something related with resolution of a scene I think..

**Comment by JanOwiesniak** [comment]
Honestly i have no idea. Just because i'm reading `UnityExport/Classes/Unity/MetalHelper.mm`, have you tried to remove metal from the Graphics API?

> IOS Platform:
> 
> Other Settings find the Rendering part, uncheck the Auto Graphics API and select only OpenGLES2.

https://github.com/f111fei/react-native-unity-view#configure-player-settings

**Comment by alisherakb** [comment]
> Honestly i have no idea. Just because i'm reading `UnityExport/Classes/Unity/MetalHelper.mm`, have you tried to remove metal from the Graphics API?
> 
> > IOS Platform:
> > Other Settings find the Rendering part, uncheck the Auto Graphics API and select only OpenGLES2.
> 
> https://github.com/f111fei/react-native-unity-view#configure-player-settings

Downgrading react-native-unity-view to 1.2.1 fixed the issue. 
The newer versions create UnityNativeModule.h which causes somehow an error with our stack (Unity3d/ARFoundation + RN).

**Comment by mistakelly** [comment]
educative discussion, it did helped out.
