### ISSUE TITLE
fatal error: 'os/c-api/il2cpp-config-platforms.h' file not found

### ISSUE THREAD

**Issue by ziyoshams** [f111fei/react-native-unity-view#99]
Just upgraded from RN 0.56 to 0.57 and getting this error. This is with Legacy Build Systems. Otherwise RN will throw millions of errors.   
Wondering if anyone has come across this.
```
In file included from /Users/ziyo/.../UnityExport/Classes/Native/Bulk_Assembly-CSharp_1.cpp:1:
In file included from /Users/ziyo/.../UnityExport/Libraries/libil2cpp/include/il2cpp-config.h:12:
/Users/ziyo.../UnityExport/Libraries/libil2cpp/include/os/c-api/il2cpp-config-api-platforms.h:3:10: fatal error: 'os/c-api/il2cpp-config-platforms.h' file not found
#include "os/c-api/il2cpp-config-platforms.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by alisherakb** [comment]
As a workaround we downgraded react-native-unity-view: 1.2.1

**Comment by ziyoshams** [comment]
Doesn't work for me.

**Comment by ziyoshams** [comment]
Fixed: I used Unity Version `2018.2.17` to export the builds.

**Comment by alisherakb** [comment]
> Fixed: I used Unity Version `2018.2.17` to export the builds.

Have you upgraded to 2018.3.+? If yes, how did you overcome that issue?

**Comment by sburaksak** [comment]
@alisherakb Did you solve this error?

**Comment by ziyoshams** [comment]
For anyone who is trying to use latest Unity i can confirm that this package works very well https://github.com/asmadsen/react-native-unity-view
